CREATE TABLE [dbo].[Action]
(
	[Id]		TINYINT NOT NULL IDENTITY(1,1),
	[Name]		VARCHAR(40) NOT NULL,
	[Text]		VARCHAR(100) NOT NULL,
	[Icon]		VARCHAR(100) NULL,
	[Url]		VARCHAR(100) NULL,
	[IsGroup]	BIT NOT NULL DEFAULT 0,
	[Parent]	TINYINT NULL,
	[Order]		SMALLINT NOT NULL DEFAULT 0,
	CONSTRAINT pkAction PRIMARY KEY([Id]),
	CONSTRAINT uqAction UNIQUE([Name]),
	CONSTRAINT fkActionParent FOREIGN KEY([Parent]) REFERENCES [Action]([Id])
)